Prep javascript functions - Anthony Pineda
Anthony-Pineda/prep-1121-code-solutions pull request #12
Opened 2021-11-18 20:01 UTC by Anthony-Pineda

![Screenshot 2021-11-18 103219](https://user-images.githubusercontent.com/93688727/142488183-82c981a1-3329-410b-a85d-842d2ad31bfd.jpg)
![Screenshot 2021-11-18 104757](https://user-images.githubusercontent.com/93688727/142488186-59cfe90e-4c3b-475d-9b53-a80f52b310ed.jpg)
![Screenshot 2021-11-18 110257](https://user-images.githubusercontent.com/93688727/142488188-4a9a4a35-343b-4ea0-9d5b-50a6fb622597.jpg)
![Screenshot 2021-11-18 111334](https://user-images.githubusercontent.com/93688727/142488190-22047dd5-49c5-4538-a311-8701bbf84f37.jpg)
![Screenshot 2021-11-18 111700](https://user-images.githubusercontent.com/93688727/142488193-ffa0a5be-506a-4575-b755-21fe7e347683.jpg)
![Screenshot 2021-11-18 112049](https://user-images.githubusercontent.com/93688727/142488194-b4ad0ad4-e372-4766-9693-95b813e30f8e.jpg)
![Screenshot 2021-11-18 113915](https://user-images.githubusercontent.com/93688727/142488195-8ea7f71a-7385-4adc-b68d-e97d52ee3777.jpg)
![Screenshot 2021-11-18 114424](https://user-images.githubusercontent.com/93688727/142488197-0020cb34-6a2e-4e68-8d62-eac09e5726c8.jpg)
![Screenshot 2021-11-18 115725](https://user-images.githubusercontent.com/93688727/142488199-4cb3deec-8199-4b4d-99d2-e69870456265.jpg)

2021-11-19 00:39 UTC, thebearingedge requested changes

2021-11-19 00:39 UTC, thebearingedge commented on prep-javascript-functions/main.js
> +console.log(cubeResult);
Hi Anthony, please put all of your functions in `main.js`

2021-11-24 02:34 UTC, Anthony-Pineda commented
![Screenshot 2021-11-23 183218](https://user-images.githubusercontent.com/93688727/143161088-a0fb2d69-b1b9-466d-89eb-daf93ae121b2.jpg)

added all functions to main.js, thanks!

2021-11-24 03:17 UTC, thebearingedge requested changes

2021-11-24 03:17 UTC, thebearingedge commented on prep-javascript-functions/main.js
> +var convertHoursToMinutesResult = convertHoursToMinutes(4);
Try multiplying `hours` times `60` so that your function works with more than just `4`.

2021-11-24 03:17 UTC, thebearingedge commented on prep-javascript-functions/main.js
> +}
Similarly with these functions, try using your parameters so that the functions can work with different values.

2021-11-25 00:24 UTC, Anthony-Pineda commented
![Screenshot 2021-11-24 162120](https://user-images.githubusercontent.com/93688727/143328691-949349d8-a30b-4add-81a2-d5d22b6b6f17.jpg)
thanks for the feedback, i believe i have resolved the issues with the parameters.

2021-11-25 00:50 UTC, thebearingedge approved these changes
Got it!

2021-11-25 00:51 UTC, merged