completed prep-css-syntax
Anthony-Pineda/prep-1121-code-solutions pull request #5
Opened 2021-11-10 04:55 UTC by Anthony-Pineda

![Screenshot 2021-11-09 205231](https://user-images.githubusercontent.com/93688727/141052282-699a62f6-6493-41ff-aca0-1e79a399f230.jpg)

2021-11-10 16:33 UTC, thebearingedge requested changes

2021-11-10 16:33 UTC, thebearingedge commented on prep-css-syntax/index.html
> +      <title>CSS Syntax</title>
Be careful to only put CSS code inside of your `<style></style>` element.

2021-11-11 01:37 UTC, Anthony-Pineda commented
![Screenshot 2021-11-10 173254](https://user-images.githubusercontent.com/93688727/141221292-6d0eacb3-80eb-411e-a893-13c0196b5afb.jpg)

thanks Tim, i have updated the placing of the style elements and fixed the italic typo

2021-11-11 15:32 UTC, thebearingedge approved these changes

2021-11-11 23:03 UTC, merged