completed prep-javascript-variables - Anthony Pineda
Anthony-Pineda/prep-1121-code-solutions pull request #9
Opened 2021-11-16 02:11 UTC by Anthony-Pineda

![Screenshot 2021-11-15 180730](https://user-images.githubusercontent.com/93688727/141883130-778253dd-0fca-4c1b-bb11-89bc01de1048.jpg)

2021-11-16 18:07 UTC, thebearingedge requested changes

2021-11-16 18:07 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +      var numberofpets = '0';
Here you should leave out the quotation marks so that JavaScript knows that `numberOfPets` should be a number and not a string.

2021-11-17 01:50 UTC, Anthony-Pineda commented
![Screenshot 2021-11-16 174733](https://user-images.githubusercontent.com/93688727/142094427-fa061992-03f1-455a-a62f-e1dcb70200a3.jpg)

Thanks, i have made the updates to my code

2021-11-17 01:51 UTC, thebearingedge approved these changes

2021-11-17 01:52 UTC, merged